name: Thread Dump Workflow

on:
  #schedule:
   #- cron: '*/5 * * * *'  # Run the workflow every 5 minutes
   push:

jobs:
  thread-dump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Get file content
        id: get-file-content
        run: |
          FILE_CONTENT=$(cat take-thread-dump.sh)
          echo "::set-output name=file_content::$FILE_CONTENT"

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Replace with your AWS region

     # Extract file content from the previous step
       # FILE_CONTENT="${{ steps.get-file-content.outputs.file_content }}"

       # Send command to AWS Systems Manager with file content
      - name: Run shell script
        run: |
                FILE_CONTENT="${{ steps.get-file-content.outputs.file_content }}"
                COMMAND_ID=$(aws ssm send-command \                                                                                           
                            --instance-ids "i-0f8d918e0d566d9f9" \
                            --document-name "AWS-RunShellScript" \
                            --comment "Take thread dump" \
                            --parameters "$(jq -n --arg content "$FILE_CONTENT" '{"commands":["echo \($content) | base64 --decode > take-thread-dump.sh", "chmod +x take-thread-dump.sh", "mv take-thread-dump.sh /home/ubuntu", "/home/ubuntu/take-thread-dump.sh"]}' )" \
                            --query 'Command.CommandId' \
                            --output text)
                echo "Command ID: $COMMAND_ID"
      
                # Wait for command completion
                sleep 5s  # Wait for 5 seconds before retrieving command output
                aws ssm list-command-invocations --command-id "${COMMAND_ID}" --details --query "CommandInvocations[].CommandPlugins[].Output"
                aws ssm get-command-invocation --command-id "${COMMAND_ID}" --instance-id "i-0f8d918e0d566d9f9" --output text --query "StandardOutputContent" > thread-dump.txt
                echo "Thread dump saved to thread-dump.txt"

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: thread-dump
          path: thread-dump.txt
